import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'

const handleChange = () => {
  axios
    .get("http://127.0.0.1:3030/batik/list", {headers: 
          {  
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*'}
          })
    .then(res => {
      console.log(res);
    })
    .catch(err => {
      console.log(err);
    })
};

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Batik Convnet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Cabin&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@400&family=Cabin&display=swap" rel="stylesheet"></link>
      </Head>

      <main className="w-full antialiased bg-white">
        <div className="flex flex-col">
          <nav className="flex justify-around py-4 bg-white/80
            backdrop-blur-md shadow-md w-full
            fixed top-0 left-0 right-0 z-10">

            <div className="flex items-center">
                <a className="cursor-pointer">
                    <h3 className="text-2xl font-medium text-blue-500">
                        <img
                            className="h-10 object-cover"
                            alt="img"
                            src="https://stackoverflow.design/assets/img/logos/so/logo-stackoverflow.svg"
                        />
                    </h3>
                </a>
            </div>

            <div className="items-center hidden w-80 lg:flex"></div>

            <div className="flex items-center space-x-6">
                <a className="flex text-gray-600 hover:text-blue-500
                    cursor-pointer transition-colors duration-300">
                    Batik Sets
                </a>
                <a className="flex text-gray-600 hover:text-blue-500
                    cursor-pointer transition-colors duration-300">
                    Algorithm
                </a>
                <a className="flex text-gray-600 hover:text-blue-500
                    cursor-pointer transition-colors duration-300">
                    About
                </a>
            </div>
          </nav>
        </div>

        <section className="header relative pt-16 items-center flex h-screen max-h-860-px">
          <div className="container mx-auto items-center flex flex-wrap">
            <div className="w-full md:w-8/12 lg:w-6/12 xl:w-6/12 pl-20">
              <div className="pt-32 sm:pt-0">
                <h1 className="font-press-start font-semibold text-5xl text-blueGray-600">
                  Batik Convnet Identifier
                </h1>
                <p className="mt-7 text-xl leading-relaxed text-blueGray-500 font-alegreya">
                  Simple implementation of Batik motifs identifier using Convnet on top of
                  Tensorflow as a base building blocks for Machine Learning model.
                </p>
                <p className="mt-4 text-xl leading-relaxed text-blueGray-500 font-alegreya">
                  This project is focusing on comparing how effective are the two 
                  Edge Detection methods such as Canny and Sobel Operator to identify each 
                  Batik motifs on Convnet.
                </p>

                <div className="mt-12">
                  <a
                    onClick={handleChange}
                    className="min-w-auto w-40
                                bg-blue-500 p-3 px-4 rounded 
                                hover:bg-blue-500 
                                transition-colors duration-30 
                                hover:animate-pulse ease-out 
                                text-white font-semibold cursor-pointer"
                  >
                    Let's Identify
                  </a>
                </div>
              </div>
            </div>
          </div>
          <img
            className="absolute top-0 b-auto right-0 pt-16 z-0 sm:w-5/12 -mt-48 sm:mt-0 w-4/12 max-h-500-px"
            src="/img/pattern_nextjs.png"
            alt="..."
          />
        </section>


        <div className="mx-auto max-w-7xl pt-40">
          <div className="container mx-auto items-center flex flex-wrap">
            <h1 className="font-press-start text-5xl">
              Welcome to <a href="https://nextjs.org">Next.js!</a>
            </h1>

            <p className={styles.description}>
              Get started by editing{' '}
              <code className={styles.code}>pages/index.tsx</code>
            </p>

            <div>
              <form action="">
                <input type="file" name="" id=""/>
                <button type="submit" 
                        className="min-w-auto w-32 h-10 
                                  bg-blue-300 p-2 rounded-xl 
                                  hover:bg-blue-500 
                                  transition-colors duration-30 
                                  hover:animate-pulse ease-out 
                                  text-white font-semibold">
                  Identify</button>
              </form>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
