import Head from 'next/head'

const Header = () => {
    return (
        <Head>
            <title>Batik Convnet</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://fonts.googleapis.com/css2?family=Cabin&display=swap" rel="stylesheet"></link>
            <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@400&family=Cabin&display=swap" rel="stylesheet"></link>
        </Head>
    );
}

export default Header